apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb
  labels:
    app: springweb
spec:
  selector:
    matchLabels:
      app: springweb
  template:
    metadata:
      labels:
        app: springweb
    spec:
      containers:
        - name: springweb-app
          image: sumanth17121988/dockerspringweb:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

apiVersion: v1
kind: Service
metadata:
  name: "springweb-service"
  namespace: "default"
  labels:
    app: "springweb"
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: "springweb"
  type: LoadBalancer
